### ISSUE TITLE
Getting None as predicted values

### ISSUE THREAD

**Issue by rushirg** [serengil/chefboost#4] opened 2020-02-09 21:47 UTC
I am getting None as a predicted output, what would be the reason for it?

environment:
pandas==0.25.1
numpy==1.17.2
tqdm==4.36.1
Python 3.7.4

[train data](https://ideone.com/LSXPIA)  
[test data](https://ideone.com/2uOsX9)

code:
[chefboost_c45.txt](https://github.com/serengil/chefboost/files/4177937/chefboost_c45.txt)
(unable to attach .py as Github doesn't allow, hence added .txt)

output:
C4.5  tree is going to be built...
Accuracy:  79.16666666666667 % on  24  instances
finished in  0.41808056831359863  seconds
Win
Win
Win
**None**
Win
Win
Win
Win
Win
Lose
Win
Lose

Also, does the chefboost have support to get precision, recall, and f1 score?

**Comment by serengil** [comment] 2020-02-10 06:19
Your prediction features do not satisfy the built decision tree rules. This should be handled and fixed in framework. Also, currently precision, recall metrics are not calculated in the FW as well. I'll add those metrics. I plan to fix these issues tonight or tomorrow night. Thank you for your deeply explanation about issues.

**Comment by Akeem-Liburd** [comment] 2020-02-12 05:54
I am also experiencing the same issue.

**Comment by serengil** [comment] 2020-02-12 06:03
I will inform you when I updated the code. Unfortunately, I could not work on it yet.

**Comment by danialcheung** [comment] 2020-04-16 07:28
Also experiencing the same issue.

**Comment by serengil** [comment] 2020-04-25 10:38
Sorry for the late solution.

This issue is solved in chefboost=0.0.5. Please upgrade your package.

The problem was decision tree has no branch for the instance you passed. As a solution, I returned the most frequent one for the current branch in the else statement. Mean value of the sub data set for the current branch will be returned for regression problems as well.

Please inform me after you tried the new version.

**Closed by serengil** 2020-04-25 10:38 UTC

**Comment by danialcheung** [comment] 2020-04-27 07:06
works great, thanks!
